spring:
  datasource:
    url: jdbc:h2:file:${user.home}/Desktop/hsqldb/jpa
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

login:
  username: pullagura
  password: pullagura
token:
  jwtSecret: pUlLSecretKey
  jwtExpirationMs: 86400000

jwt:
  enabled: true
  client:
    signature:
      key: pUlLSecretKey
  server:
    signature:
      key: pUlLSecretKey
      issuer: heptagon
build:
  app:
    description: "heptagon sample project"
  version: "1.0.0"


#spring.datasource.url=jdbc:h2:file:${user.home}/Desktop/hsqldb/jpa
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto= update
#spring.h2.console.enabled=true
# default path: h2-console
#spring.h2.console.path=/h2-console

#login.username=pullagura
#login.password=pullagura
#token.jwtSecret=pUlLSecretKey
#token.jwtExpirationMs=86400000
