#server:
  #servlet:
    #context-path: /hg

spring:
  datasource:
    url: jdbc:h2:file:${user.home}/Desktop/hsqldb/jpa
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

  mail:
    host: smtp.gmail.com
      username: rajujwala2@gmail.com
      password: Raju@np3
      port: 587
      properties:
        mail:
          smtp:
            auth: true
              starttls:
                enable: true

login:
  username: pullagura
  password: pullagura
token:
  jwtSecret: pUlLSecretKey
  jwtExpirationMs: 1000

to:
  email: pullagura.lakshmidevi@heptagon.in

otp:
  subject: OTP StudentService

jwt:
  enabled: true
  client:
    signature:
      key: pUlLSecretKey
  server:
    signature:
      key: pUlLSecretKey
      issuer: heptagon
build:
  app:
    description: "heptagon sample project"
  version: "1.0.0"
