#server:
  #servlet:
    #context-path: /hg

spring:
  datasource:
    url: jdbc:h2:file:${user.home}/Desktop/hsqldb/jpa
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

login:
  username: pullagura
  password: pullagura
token:
  jwtSecret: pUlLSecretKey
  jwtExpirationMs: 86400000

jwt:
  enabled: true
  client:
    signature:
      key: pUlLSecretKey
  server:
    signature:
      key: pUlLSecretKey
      issuer: heptagon
build:
  app:
    description: "heptagon sample project"
  version: "1.0.0"
